### ISSUE TITLE
Display flickering issue on X540LA

### ISSUE THREAD

**Issue by ramanverma2k** [shammu2bd/Asus-X540LJ-Hackintosh-OpenCore#3]
Hi, the display is constantly flickering on ASUS X540LA with identical configuration as yours.

CPU: i3 5005u
iGPU: intel HD 5500.
macOS: BigSur (also tried to boot Monterey but it didn't even boot into installer screen)

Any ideas on what to do?
I've tried editing the DeviceInfo and matching the device-id and etc. Also tried updating the WhateverGreen kext but that didn't boot either.

**Comment by ramanverma2k** [comment]
After hours of smashing head and frustration, I was able to solve it by using WhateverGreen-1.6.1-DEBUG kext and following BIOS settings.

Reset BIOS to default settings then change these options only.
DVMT -> 64MB
Launch CSM -> Disabled

**Comment by ramanverma2k** [comment]
Unfortunately, the flickering remains in Monterey even after using the above settings. Not sure what is happening here.

**Comment by shammu2bd** [comment]
You don't need to change WhateverGreen.kext. Use my one that is included in my github.  DVMT should work by default bios settings. But, I will update latest EFI soon. And give me some time today I will update latest OC version.

**Comment by shammu2bd** [comment]
macOS 12 Monterey only works if built-in WIFI kext is disabled. If you really want to use macOS 12 then you have to use additional WIFI adapter and turn off build-in WIFI kext.

**Comment by shammu2bd** [comment]
Show me the video of display flickering pattern and also the about section of macOS.

**Comment by ramanverma2k** [comment]
Haven't installed Monterey because the display flickers right on installer screen. BigSur works properly though.

Should I install Monterey and give you the details that you asked for?

**Comment by ramanverma2k** [comment]
> macOS 12 Monterey only works if built-in WIFI kext is disabled. If you really want to use macOS 12 then you have to use additional WIFI adapter and turn off build-in WIFI kext.

I don't really care about WiFi as long as the OS and Ethernet works. I have need to use this machine temporarily for development purpose only.

**Comment by shammu2bd** [comment]
Before installing macOS 12 disable these three kexts in EFI (AirPortAtheros40.kext, HS80211Family.kext, WifiLocFix.kext). Let me know if it works.

**Comment by ramanverma2k** [comment]
> Before installing macOS 12 disable these three kexts in EFI (**AirPortAtheros40.kext**, **HS80211Family.kext**, **WifiLocFix.kext**). Let me know if it works.

Sure, I'm trying to install Monterey right now.

BTW did you face any issues related to Audio on BigSur? 

Everything works great except for when i connect my TV or Monitor over HDMI, I only get video and no audio. In sound and output devices it recognizes the TV or Monitor speakers.

**Comment by shammu2bd** [comment]
Didn't face any issue in audio. But not sure about secondary device HDMI audio. Tonight I will check it.

**Comment by ramanverma2k** [comment]
@shammu2bd Nevermind that flickering was related to my laptop display. Manually lowering and cranking the brightness fixes it and doesn't happen again. Only have to bear it until the installation process.

BTW on a completely different topic,
Got Ventura booted up and Hardware Acceleration is working as well.
![PXL_20221127_172519634.jpg](https://user-images.githubusercontent.com/59292838/204134972-77a38535-6dda-4c39-9b7a-114d6a4f2948.jpg)

**Comment by ramanverma2k** [comment]
Got everything working for my usage.

Working:
- Display & Hardware Acceleration
- Ethernet
- USB Tethering
- Audio & Digital Audio (HDMI)

Not working:
- Bluetooth
- Wifi
- Some FN keys (although Volume & Brightness keys do work).
- Don't really care about anything else.

**Comment by shammu2bd** [comment]
Bluetooth and WIFI both devices come with the same chip of **Qualcomm Atheros**. That's why both are not working.  I have already mentioned in github that all FN keys not works.

**Comment by shammu2bd** [comment]
Is your HDMI Audio working? Mine is not working. Even 4K resolution not supporting.  I will patch my EFI later.

**Comment by ramanverma2k** [comment]
> Is your HDMI Audio working? Mine is not working. Even 4K resolution not supporting.  I will patch my EFI later.

Yes i got it to work by patching with Hackintool. There was a thread on insanelymac which explained how to patch it. I'll link it if i find it again.

**Comment by rednexx46** [comment]
> @shammu2bd Nevermind that flickering was related to my laptop display. Manually lowering and cranking the brightness fixes it and doesn't happen again. Only have to bear it until the installation process.
> 
> BTW on a completely different topic,
> Got Ventura booted up and Hardware Acceleration is working as well.
> ![PXL_20221127_172519634.jpg](https://user-images.githubusercontent.com/59292838/204134972-77a38535-6dda-4c39-9b7a-114d6a4f2948.jpg)

what product name did you use, to work?

**Comment by ramanverma2k** [comment]
> 

Support for MacBookPro 12,1 was dropped in Ventura so I used iMac19,1 for initial booting and setup then later on changed back to MacBookPro 12,1 and added amfi workaround and lowered sip level.

**Comment by ramanverma2k** [comment]
I am closing this issue as my initial problem about display was fixed.

Here's the link to my repository if you need it for reference.
https://github.com/ramanverma2k/X540LA-Hackintosh

**Comment by shammu2bd** [comment]
@rednexx46 @maranix I have released macOS Sequoia 15 EFI which support built-in wifi. check this out:  https://github.com/shammu2bd/Asus-X540LJ-Hackintosh-macOS-Sequoia-OpenCore

**Comment by maranix** [comment]
@shammu2bd Thanks for keeping it alive hopefully, it'll come in handy for somebody who really needs it or is hacking their way to macOS but I already bought a MacBook last year since my work required it.
